---
title: "Day 1"
output:
  html_document:
    df_print: paged
---

```{r}

library(tidyverse)
library(fs)
```

# get drift

## read data

```{r}

validation_log <- 

    # get paths of all .csv-files in all subdirectories
    dir_ls("log_drift", recursive = TRUE, glob = "*.csv") %>%

    # for each file, map as data frame
    map_df(read_tsv, col_types=cols(subject_id = col_character())) %>%

    # define column types
    mutate_at(vars(subject_id, video_id, validation_point),
              list(~factor(.))) %>%
    
    # in zukunft überfüllig
    rename(video_part = session_id) %>% 

    mutate_at(vars(video_part, validation_id, validation_time),
              list(~ordered(.))) %>%

    # remove frames with failed eye tracking
    filter(gaze_x > 0, gaze_y > 0) %>%

    mutate(
        # frame_id = as.integer(frame_id),

        # extract video_id (remove video_part)
        video_id = str_sub(video_id, 1,-3),

        # sort validation id: pre before post
        validation_id = ordered(validation_id, levels =c("pre", "post")), 

        # random checking, why control_x/y might be NA showed perfect fixation
        control_x = case_when(is.na(control_x) ~ gaze_x,
                              !is.na(control_x) ~ control_x),
        control_y = case_when(is.na(control_y) ~ gaze_y,
                              !is.na(control_y) ~ control_y),
        
        # calculate difference for gaze_x/y from control_x/y
        diff_x = control_x - gaze_x,
        diff_y = control_y - gaze_y)

```

## get summary

```{r}

# setting sd limit to later exclude fixations
sd_limit <- 2.5

# get summary statistics
validation_summary <- validation_log %>% 

    # for each session in validation in subject
    group_by(subject_id, validation_id, video_part) %>% 

    summarise(

        # get means
        m_x = mean(diff_x),
        m_y = mean(diff_y),

        # get sd
        sd_x = sd(diff_x),
        sd_y = sd(diff_y),

        # set limit to exclude fixations off by sd_limit*sd
        limit_x = sd_limit*sd_x,
        limit_y = sd_limit*sd_y)

```

## integrate summary with log

```{r}

validation_log <-

    validation_log %>%

    left_join(
        validation_summary,
        by=c("subject_id", "video_part", "validation_id")) %>%

    # indicate fixations differing more then limit
    mutate(
        bl_y_ok = case_when(diff_y < limit_y ~ "ok",
                            diff_y >= limit_y ~ "not ok"),
        bl_x_ok = case_when(diff_x < limit_x ~ "ok",
                            diff_x >= limit_x ~ "not ok"),
        bl_ok = case_when(
            (bl_x_ok == "ok" & bl_y_ok == "ok") ~ "ok",
            (bl_x_ok != bl_y_ok) ~ "not ok",
            (bl_x_ok == "not ok" & bl_y_ok == "not ok") ~ "not ok"))

```

## get pre-post comparison

```{r}

validation_pre_post <-

    validation_log %>%

    filter(bl_ok == "ok") %>%

    group_by(subject_id, video_part, validation_id) %>% 

    summarise(
        m_x = mean(diff_x),
        m_y = mean(diff_y)) %>%

    gather(temp, diff, c("m_x", "m_y")) %>%

    unite(temp1, video_part, temp, sep="_") %>%

    unite(temp2, validation_id, temp1, sep = "_") %>%

    spread(temp2, diff) %>% 
    mutate(change_1_x = post_1_m_x - pre_1_m_x,
           change_1_y = post_1_m_y - pre_1_m_y,
           change_2_x = post_2_m_x - pre_2_m_x,
           change_2_y = post_2_m_y - pre_2_m_y) %>% 
    select(subject_id,
           start_1_x = pre_1_m_x, change_1_x, start_1_y = pre_1_m_y, change_1_y,
           start_2_x = pre_2_m_x, change_2_x, start_2_y = pre_2_m_y, change_2_y)

```

## plot fixation per

```{r validation plots}

### plots for baseline quality per subject
validation_quality <- validation_log %>%

    mutate(

        # move points specific to color
        diff_x= case_when(
            validation_point=="green" ~ diff_x,
            validation_point=="blue" ~ diff_x + 25,
            validation_point=="red" ~ diff_x - 25),

        diff_y = case_when(
            validation_point=="green" ~ diff_y + 25,
            validation_point=="blue" ~ diff_y - 25,
            validation_point=="red" ~ diff_y - 25)) %>%
    
    # filter if wanted, but later indicated by 
    # filter(bl_y_ok == "ok", bl_x_ok == "ok" ) %>% 

    ### for each subject
    group_by(subject_id) %>%

    ### for each subject, put all data in a list
    nest() %>%

    ### make a list of plots for each subject
    mutate(
        plot = map(
            data,
            
            ### on data use this funciton (per row I think)
            ~ ggplot(.) +

                geom_hline(yintercept=0, size = .05) +
                geom_vline(xintercept=0, size = .05) +

                ### add fixation points
                geom_point(
                    aes(x=0, y=25),
                    shape = 21, colour = "green", fill = "white",
                    size = 3, stroke = 1) +
                geom_point(
                    aes(x=25, y=-25),
                    shape = 21, colour = "blue", fill = "white",
                    size = 3, stroke = 1) +
                geom_point(
                    aes(x=-25, y=-25),
                    shape = 21, colour = "red", fill = "white",
                    size = 3, stroke = 1) +
                
                geom_point(
                    aes(diff_x, diff_y, color = validation_point, shape=bl_ok),
                    size=.5) +

                # geom_rect(
                #     aes(xmax=diff_sd_x*2.5, xmin=-diff_sd_x*2.5,
                #         ymax=diff_sd_y*2.5, ymin=-diff_sd_y*2.5,
                #         color = validation_point),
                #     alpha=0, size=.05, color="black") +

                # stat_summary(fun.xmin = function(x) sd(x),
                #              fun.xmax = function(x) sd(x),
                #              fun.ymin = function(x) sd(x),
                #              fun.ymax = function(x) sd(x),
                #              geom = "rect"),

                ### cut off x
                scale_x_continuous(limits = c(-150,150)) +

                ### no cut off y
                scale_y_continuous(limits = c(-150,150)) +

                ### scale settings
                scale_color_manual(
                    values=c("darkblue", "darkgreen", "darkred")) +
                scale_shape_manual(
                    values = c(4,16), drop = FALSE) +

                ### split plots up by session and validation
                facet_wrap(video_part~validation_id, drop = FALSE)))

# save plots
walk2(

    # for each subject
    .x = validation_quality$subject_id,

    # each plot
    .y = validation_quality$plot,

    # save
    ~ggsave(

        # name of the file
        paste0("plots/validation/subject_",
               validation_quality$subject_id[.x],
               "_validation.png"),

        .y,

        # size of the plot
        width = 7,
        height = 7))

```

# correct for video fixations 

```{r}

validation_prot <-     dir_ls("prot", glob = "*.csv") %>% 

    map_df(read_tsv, col_types=cols()) %>% 

    rename(subject_id = subject,
           video_id = value,
           video_part = part) %>% 

    # filter "val_" videos
    filter(str_detect(video_id, "val")) %>%

    mutate(
        
        subject_id = ifelse(
            str_count(subject_id) < 2,
            str_c("0", subject_id),
            subject_id)) %>% 

    group_by(subject_id, video_id) %>% 

    # when was the video played first/second
    mutate(session_id = 1:n()) %>% 

    # count again without validation videos
    group_by(subject_id, video_part) %>% 

    mutate(video_n = 1:n()) %>% ungroup() %>% 

    # define column types
    mutate_at(vars(video_id, subject_id, video_part),
              list(~factor(.))) %>% 
    mutate_at(vars(video_n, session_id),
              list(~ordered(.))) %>% 
    select(subject_id, session_id, video_id, video_part, everything())


video_prot <- 

    dir_ls("prot", glob = "*.csv") %>% 

    map_df(read_tsv, col_types=cols()) %>% 

    rename(subject_id = subject,
           video_id = value,
           video_part = part) %>% 

    # filter "val_" videos
    filter(!str_detect(video_id, "val")) %>%

    mutate(
        
        subject_id = ifelse(
            str_count(subject_id) < 2,
            str_c("0", subject_id),
            subject_id)) %>% 

    group_by(subject_id, video_id) %>% 

    # when was the video played first/second
    mutate(session_id = 1:n()) %>% 

    # count again without validation videos
    group_by(subject_id, video_part) %>% 

    mutate(video_n = 1:n()) %>% ungroup() %>% 

    # define column types
    mutate_at(vars(video_id, subject_id, video_part),
              list(~factor(.))) %>% 
    mutate_at(vars(video_n, session_id),
              list(~ordered(.))) %>% 
    select(subject_id, session_id, video_id, video_part, everything())

```


```{r}

video_log <- 

    # get paths of all .csv-files in all subdirectories
    dir_ls("log", recursive = TRUE, glob = "*.txt") %>%

    # for each file, map as data frame
    map_df(read_tsv, col_types=cols(subject_id = col_character())) %>%
    
    filter(!str_detect(video_id, "val")) %>% 
    
    rename(gaze_x = screenPos.x,
           gaze_y = screenPos.y,
           frame_id = frame_video) %>%
    separate(video_id, c("video_id", "video_part"), sep = "_") %>% 

    # define column types
    mutate_at(vars(video_id, subject_id, video_part),
              list(~factor(.))) %>% 
    select(subject_id, date, video_id, video_part, frame_id, everything())

    # cleaning


```

## integrate protocol into log

```{r}

video_log <- 

    video_log %>% 

    left_join(video_prot, by =c("subject_id", "video_id", "video_part")) %>% 
    mutate(subject_id = factor(subject_id))

```


```{r}

# Create separate files for each species
iris %>%
  split(.$Species) %>%
  map(select, -Species) %>%
  iwalk(~ write_tsv(.x, paste0(.y, ".tsv")))

```


```{r animations}

library(gganimate)

ani <-
    validation_quality$plot[[1]] +
    labs(title = 'Frame: {frame_time}') +
    transition_time(frame_id) +
    ease_aes('linear')


```

